#!/bin/bash

if [ $# -lt 3 ]; then
    echo "Usage:"
    echo "  ./create_database file [file name] [database name]"
    echo "  ./create_database [couchbase list username] [couchbase lite password] [database name]"
    exit 1
fi

if [ $1 = "file" ]; then
    file_content_array=()
    while read line; do
        file_content_array+=(${line})
    done < $2
    USRENAME=${file_content_array[0]}
    PASSWORD=${file_content_array[1]}
else
    USRENAME=$1
    PASSWORD=$2
fi
DB_NAME=$3

echo "couchbase lite username = ${USRENAME}"
echo "couchbase lite password = ******"
echo "database name = ${DB_NAME}"
echo ""

echo "curl -v -H 'Content-Type: application/json' -X PUT http://${USRENAME}:******@localhost:5984/${DB_NAME}/"
curl -v -H 'Content-Type: application/json' -X PUT http://${USRENAME}:${PASSWORD}@localhost:5984/${DB_NAME}/
