#!/bin/bash

if [ $# -lt 4 ]; then
    echo "Usage:"
    echo "  ./create_document file [file name] [database name] [json data]"
    echo "  ./create_document [couchbase list username] [couchbase lite password] [database name] '[json data]'"
    exit 1
fi

if [ $1 = "file" ]; then
    file_content_array=()
    while read line; do
        file_content_array+=(${line})
    done < $2
    USERNAME=${file_content_array[0]}
    PASSWORD=${file_content_array[1]}
else
    USERNAME=$1
    PASSWORD=$2
fi
DB_NAME=$3
JSON_DATA=$4

echo "couchbase lite username = ${USERNAME}"
echo "couchbase lite password = ******"
echo "database name = ${DB_NAME}"
echo "json data = ${JSON_DATA}"
echo ""

echo "curl -v -X POST -H 'Content-Type: application/json' -d '${JSON_DATA}' http://${USERNAME}:******@localhost:5984/${DB_NAME}/"
curl -v -X POST -H 'Content-Type: application/json' -d "${JSON_DATA}" http://${USERNAME}:${PASSWORD}@localhost:5984/${DB_NAME}/

