#!/bin/bash

if [ $# -lt 3 ]; then
    echo "Usage:"
    echo "  ./get_all_document file [file name] [database name]"
    echo "  ./get_all_document [couchbase list username] [couchbase lite password] [database name]"
    exit 1
fi

if [ $1 -eq "file" ]; then
    file_content_array=()
    while read line; do
        file_content_array+=(${line})
    done < $1
    USRENAME=${file_content_array[0]}
    PASSWORD=${file_content_array[1]}
else
    USRENAME=$1
    PASSWORD=$2
fi
DB_NAME=$3

echo "couchbase lite username = $USRENAME"
echo "couchbase lite password = ******"
echo "database name = $DB_NAME"
echo ""

echo "curl -v -X GET http://$USERNAME:******@localhost:5984/$DB_NAME/_all_docs"
curl -v -X GET http://$USERNAME:$PASSWORD@localhost:5984/$DB_NAME/_all_docs

