#!/bin/bash

if [ $# -lt 5 ]; then
    echo "Usage:"
    echo "  ./replicate file [file name] [couchbase lite database name] [syncgateway ip] [syncgateway database name]"
    echo "  ./replicate [couchbase list username] [couchbase lite password] [couchbase lite database name] [syncgateway ip] [syncgateway database name]"
    exit 1
fi

if [ $1 -eq "file" ]; then
    file_content_array=()
    while read line; do
        file_content_array+=(${line})
    done < $1
    USRENAME=${file_content_array[0]}
    PASSWORD=${file_content_array[1]}
else
    USRENAME=$1
    PASSWORD=$2
fi
CL_DB_NAME=$3
SG_IP=$4
SG_DB_NAME=$5
PUSH_JSON_DATA="{\"source\": \"$CL_DB_NAME\", \"target\": \"http://${SG_IP}/${SG_DB_NAME}/\", \"continuous\": true}"
PULL_JSON_DATA="{\"source\": \"http://${SG_IP}/${SG_DB_NAME}/\", \"target\": \"$CL_DB_NAME\", \"continuous\": true}"

echo "couchbase lite username = $USERNAME"
echo "couchbase lite password = ******"
echo "couchbase lite database name = $CL_DB_NAME"
echo "syncgateway ip = $SG_IP"
echo "syncgateway database name = $SG_DB_NAME"
echo "push json data = ${PUSH_JSON_DATA}"
echo "pull json data = ${PULL_JSON_DATA}"
echo ""

echo "curl -v -X POST -d '${PUSH_JSON_DATA}' http://$USERNAME:$PASS@localhost:5984/_replicate"
curl -v -X POST -d "${PUSH_JSON_DATA}" http://$USERNAME:$PASS@localhost:5984/_replicate

echo "curl -v -X POST -d '${PULL_JSON_DATA}' http://$USERNAME:$PASS@localhost:5984/_replicate"
curl -v -X POST -d "${PULL_JSON_DATA}" http://$USERNAME:$PASS@localhost:5984/_replicate

